// Shared navigation and honest preview interactions; no entitlement is granted here.

// --- Inject the shared navigation ---
const navEl=document.querySelector('nav.nav');
if(navEl&&!navEl.children.length){
  navEl.innerHTML=`<div class="container nav-inner"><a class="brand" href="index.html">Mission <span>&amp;</span> Method</a><button class="menu" type="button" aria-expanded="false" aria-controls="main-links">Menu</button><div class="nav-links" id="main-links"><details class="courses-dropdown nav-dropdown"><summary>Courses <span aria-hidden="true">⌄</span></summary><div class="courses-dropdown-panel"><a class="all-courses-link" href="courses.html">Explore all courses →</a><div class="course-menu-group"><a class="course-menu-title" href="planning-system.html">Planning System</a><span class="course-menu-caption">Available course</span><a href="planning-system.html#about">About this course</a><a href="planning-system.html#outcomes">Learning outcomes</a><a href="planning-system.html#modules">Modules &amp; lessons</a><a href="organisation.html">Your Organisation</a><a class="course-menu-start" href="learn.html?module=1&amp;lesson=purpose">Start learning →</a></div><div class="future-course-list" aria-label="Future courses"><span><b>Implementing System</b><small>Coming soon</small></span><span><b>Scaling Up System</b><small>Coming soon</small></span></div></div></details><details class="resources-dropdown nav-dropdown"><summary>Resources <span aria-hidden="true">⌄</span></summary><div class="courses-dropdown-panel resources-dropdown-panel"><div class="resource-menu-group"><a href="reading-library.html"><b>Evidence Library</b><small>Curated research behind every lesson</small></a><a href="software.html"><b>Impact Tools</b><small>Ethical Bridge Software Suite</small></a><a href="legal-templates.html"><b>Legal Templates</b><small>Contracts, policies, consent forms</small></a><a href="experts.html"><b>Work with our experts</b><small>Specialist support when you need it</small></a></div></div></details><a href="pricing.html">Pricing</a><a href="about.html">About</a><a class="contact-link" href="contact.html">Contact</a><a class="account-link" href="account.html">Sign in</a></div></div>`;
}

// --- Bind nav interactions (works whether the nav was injected or hard-coded) ---
const menu=document.querySelector('.menu'),links=document.querySelector('.nav-links');
const dropdowns=document.querySelectorAll('details.nav-dropdown, details.courses-dropdown');
dropdowns.forEach(dd=>{
  dd.addEventListener('keydown',event=>{if(event.key==='Escape'&&dd.open){event.stopPropagation();dd.open=false;dd.querySelector('summary').focus();}});
  dd.addEventListener('focusout',event=>{if(!dd.contains(event.relatedTarget))dd.open=false;});
  dd.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{dd.open=false;links?.classList.remove('open');menu?.setAttribute('aria-expanded','false');}));
});
document.addEventListener('click',event=>{dropdowns.forEach(dd=>{if(!dd.contains(event.target))dd.open=false;});});
menu?.addEventListener('click',()=>{const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&links?.classList.contains('open')){links.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.focus();}});

// --- Active-state highlighting for the current page ---
const page=location.pathname.split('/').pop()||'index.html';
const coursePages=['courses.html','planning-system.html','learn.html','organisation.html','strategic-foundation.html','theory-of-change.html','team-organisation.html','organisation-systems.html','policies-procedures.html','strategy-to-action.html','business-model.html','fundraising-partnerships.html'];
const resourcePages=page=>page==='reading-library.html'||page==='software.html'||page==='legal-templates.html'||page==='experts.html'||page.startsWith('software-')||page.startsWith('legal-templates-');
if(coursePages.includes(page))document.querySelector('.courses-dropdown')?.classList.add('active');
if(resourcePages(page))document.querySelector('.resources-dropdown')?.classList.add('active');
document.querySelectorAll('.nav-links a').forEach(a=>{const path=a.getAttribute('href');if(path===page||(path==='courses.html'&&['learn.html','planning-system.html','organisation.html'].includes(page))||(path==='software.html'&&page.startsWith('software-'))||(path==='legal-templates.html'&&page.startsWith('legal-templates-'))){a.classList.add('active');a.setAttribute('aria-current','page');}else a.classList.remove('active');});

// --- Generic UI wiring ---
document.querySelectorAll('[data-accordion]').forEach(item=>{const button=item.querySelector('button');button?.addEventListener('click',()=>{const open=item.classList.toggle('open');button.setAttribute('aria-expanded',String(open));const marker=button.querySelector('i');if(marker)marker.textContent=open?'−':'+';});});
document.querySelectorAll('[data-course-tab]').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('[data-course-tab]').forEach(t=>t.classList.toggle('active',t===tab));document.querySelectorAll('[data-course-panel]').forEach(p=>p.classList.toggle('active',p.dataset.coursePanel===tab.dataset.courseTab));}));
document.querySelectorAll('[data-subscribe]').forEach(b=>b.addEventListener('click',()=>location.href='subscribe.html'));
document.querySelectorAll('[data-scroll]').forEach(b=>b.addEventListener('click',()=>document.querySelector(b.dataset.scroll)?.scrollIntoView()));
function openLinkedReading(){if(!location.hash)return;let id;try{id=decodeURIComponent(location.hash.slice(1));}catch{return;}const target=document.getElementById(id);if(target?.tagName==='DETAILS')target.open=true;}
openLinkedReading();window.addEventListener('hashchange',openLinkedReading);

// --- Footer injection (unchanged) ---
const footer=document.querySelector('footer');if(footer){const style=document.createElement('link');style.rel='stylesheet';style.href='footer.css?v=nav3';document.head.append(style);const nfr=document.createElement('link');nfr.rel='stylesheet';nfr.href='nav-footer-redesign.css?v=nfr1';document.head.append(nfr);footer.className='site-footer';footer.innerHTML=`<div class="container footer-map"><div class="footer-brand-column"><a class="brand" href="index.html">Mission <span>&</span> Method</a><p>Practical learning, trusted evidence and impact tools for purpose-led organisations.</p><a class="ethical-link" href="https://ethicalbridge.org/" target="_blank" rel="noopener">Part of the Ethical Bridge ecosystem ↗</a></div><div><h3>Platform</h3><a href="courses.html">Courses</a><a href="planning-system.html">Planning System</a><a href="reading-library.html">Evidence Library</a><a href="software.html">Impact Tools</a><a href="legal-templates.html">Legal Templates</a><a href="pricing.html">Pricing &amp; packages</a><a href="experts.html">Work With Our Experts</a></div><div><h3>Organisation</h3><a href="about.html">About Mission &amp; Method</a><a href="founder-profile.html">Founder profile</a></div><div><h3>Help &amp; access</h3><a href="read-me.html">Start here</a><a href="planning-system.html#faq">Frequently asked questions</a><a href="organisation.html">Your Organisation</a><a href="account.html">Account</a></div><div><h3>Legal &amp; trust</h3><a href="legal.html#privacy">Privacy</a><a href="legal.html#terms">Terms</a><a href="legal.html#cookies">Storage &amp; cookies</a><a href="legal.html#accessibility">Accessibility</a><a href="legal.html#security">Security</a><a href="legal.html#educational">Educational guidance</a><a href="legal.html#copyright">Sources &amp; copyright</a></div></div><div class="container footer-contact"><div><span>Questions, partnerships or support</span><b>Talk to Mission &amp; Method</b></div><a class="footer-contact-button" href="contact.html">Contact us →</a></div><div class="container footer-bottom"><span>© 2026 Mission &amp; Method</span><span><span id="pricing-currency">Development preview</span></span></div>`;}
const contact=document.querySelector('#contact-form');if(contact){const note=document.createElement('p');note.className='contact-note';note.textContent='Contact delivery is not connected yet. You can draft and download your message here; it will not be sent.';contact.before(note);contact.querySelector('button[type=submit]').textContent='Download message draft';contact.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(contact);const text=`Name: ${data.get('name')}\nEmail: ${data.get('email')}\n\n${data.get('message')}`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='mission-method-message.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);contact.querySelector('.form-message').textContent='Draft downloaded. No message has been sent.';});}

import('./pricing-config.js').then(({pricing})=>{const label=document.querySelector('#pricing-currency');if(label)label.textContent='Development preview · '+pricing.currency+' pricing';});
