// Consultant details are kept together so future calendar/CRM integrations can use one source.
const consultants = [
  {id:'julieta',name:'Julieta Castiñeira de Dios',role:'NGO Strategy, Programmes & Organisational Foundations',summary:'Mission, vision and values; theory of change; strategic planning; fundraising; donor compliance; programme design; MEAL; partnerships and organisational development.',days:[1,3],hours:[8,9,10,11],schedule:'Monday and Wednesday · 08:00–12:00 WIB',button:'Book with Julieta',image:'assets/experts/julieta.png'},
  {id:'marketing',name:'Marketing Specialist',role:'Marketing, Communications & Brand Strategy',summary:'Brand positioning; communications strategy; social media; storytelling; website messaging; audience growth; campaigns; content planning and visual identity.',days:[2,4],hours:[10,11,12,13],schedule:'Tuesday and Thursday · 10:00–14:00 WIB',button:'Book a marketing consultation',image:'assets/experts/marketing.png'},
  {id:'startup',name:'Startup Strategy Specialist',role:'Startup Strategy, Growth & Business Foundations',summary:'Business models; market positioning; product strategy; growth planning; partnerships; operations; investor readiness; revenue and social enterprise development.',days:[1,4,5],hours:[13,14,15,16],schedule:'Monday, Thursday and Friday · 13:00–17:00 WIB',button:'Book a startup consultation',image:'assets/experts/startup.png'},
  {id:'digital',name:'Web Development Specialist',role:'Programming, Digital Tools & Web Development',summary:'Website strategy; platform design; user journeys; no-code and custom tools; CRM setup; digital systems; automation; web development and technical scoping.',days:[2,3,5],hours:[9,10,11,12],schedule:'Tuesday, Wednesday and Friday · 09:00–13:00 WIB',button:'Book a digital consultation',image:'assets/experts/digital.png'}
];
const areas=[...document.querySelectorAll('#areas-list li')].map(item=>item.textContent.trim());
const grid=document.querySelector('#expert-grid');
const bookingDialog=document.querySelector('#booking-dialog');
const proposalDialog=document.querySelector('#proposal-dialog');
const bookingOriginal=document.querySelector('#booking-content').innerHTML;
const proposalOriginal=document.querySelector('#proposal-content').innerHTML;
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
grid.innerHTML=consultants.map(c=>`<article class="expert-card"><img src="${c.image}" alt="Illustrated portrait of the ${escapeHtml(c.name)} consultation profile" loading="lazy"><div class="expert-body"><span class="eyebrow">Meet the team</span><h3>${escapeHtml(c.name)}</h3><p class="expert-role">${escapeHtml(c.role)}</p><p class="expert-summary">${escapeHtml(c.summary)}</p><div class="expert-meta"><span>${escapeHtml(c.schedule)}</span><strong>USD 49 / 1 hour</strong></div><button class="button" type="button" data-book="${c.id}">${escapeHtml(c.button)}</button></div></article>`).join('');

// Re-query form controls after a successful prototype submission is reset.
function bookingControls(){return {form:document.querySelector('#booking-form'),person:document.querySelector('#booking-professional'),date:document.querySelector('#booking-date'),time:document.querySelector('#booking-time'),local:document.querySelector('#local-time')};}
function upcomingDates(consultant){const now=new Date();const dates=[];for(let offset=1;offset<=28&&dates.length<8;offset++){const d=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()+offset));if(consultant.days.includes(d.getUTCDay()))dates.push(d.toISOString().slice(0,10));}return dates;}
function refreshDates(){const c=consultants.find(x=>x.id===bookingControls().person.value);const {date}=bookingControls();date.innerHTML=c?upcomingDates(c).map(value=>`<option value="${value}">${new Intl.DateTimeFormat('en',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(value+'T00:00:00Z'))}</option>`).join(''):'<option value="">Select a professional first</option>';refreshTimes();}
function refreshTimes(){const c=consultants.find(x=>x.id===bookingControls().person.value);const {time}=bookingControls();time.innerHTML=c?c.hours.map(hour=>`<option value="${String(hour).padStart(2,'0')}:00">${String(hour).padStart(2,'0')}:00 WIB</option>`).join(''):'<option value="">Select a professional first</option>';refreshLocal();}
function refreshLocal(){const {date,time,local}=bookingControls();if(!date.value||!time.value){local.textContent='All slots are shown in WIB (UTC+7).';return;}const utc=new Date(`${date.value}T${String(Number(time.value.slice(0,2))-7).padStart(2,'0')}:00:00Z`);try{local.textContent=`Your local time: ${new Intl.DateTimeFormat(undefined,{dateStyle:'full',timeStyle:'short'}).format(utc)} (${Intl.DateTimeFormat().resolvedOptions().timeZone}).`;}catch{local.textContent='All slots are shown in WIB (UTC+7).';}}
function openBooking(id){if(!document.querySelector('#booking-form'))document.querySelector('#booking-content').innerHTML=bookingOriginal;const {person,form,date,time}=bookingControls();person.innerHTML=consultants.map(c=>`<option value="${c.id}">${escapeHtml(c.name)} — ${escapeHtml(c.role)}</option>`).join('');person.value=id||'julieta';refreshDates();person.onchange=refreshDates;date.onchange=refreshLocal;time.onchange=refreshLocal;form.onsubmit=event=>{event.preventDefault();if(!form.reportValidity())return;const c=consultants.find(x=>x.id===person.value);const chosen=`${date.options[date.selectedIndex].text} at ${time.value} WIB`;document.querySelector('#booking-content').innerHTML=`<div class="form-success" role="status"><strong>Prototype booking confirmed</strong><p>Your one-hour consultation with ${escapeHtml(c.name)} is selected for ${escapeHtml(chosen)}. Price: USD 49.</p><small>This preview has not reserved a live calendar slot or taken payment. A calendar and payment provider must be connected before bookings are accepted.</small></div>`;};bookingDialog.showModal();}
grid.addEventListener('click',event=>{const button=event.target.closest('[data-book]');if(button)openBooking(button.dataset.book);});
function setupProposal(){if(!document.querySelector('#proposal-form'))document.querySelector('#proposal-content').innerHTML=proposalOriginal;const form=document.querySelector('#proposal-form');const areaField=document.querySelector('#proposal-areas');areaField.innerHTML='<legend>Areas where you need support — select at least one</legend>'+areas.map(area=>`<label><input type="checkbox" name="areas" value="${escapeHtml(area)}">${escapeHtml(area)}</label>`).join('');areaField.addEventListener('change',()=>{if(form.querySelector('[name="areas"]:checked'))areaField.querySelector('input').setCustomValidity('');});form.onsubmit=event=>{event.preventDefault();if(!form.reportValidity())return;if(!form.querySelector('[name="areas"]:checked')){areaField.querySelector('input').setCustomValidity('Select at least one area.');areaField.querySelector('input').reportValidity();return;}document.querySelector('#proposal-content').innerHTML='<div class="form-success" role="status"><strong>Thank you — your request is ready.</strong><p>Our team would review your needs and contact you with next steps and, where appropriate, a tailored proposal.</p><small>This is a prototype form. Your request has not been sent to Mission &amp; Method yet.</small></div>';};proposalDialog.showModal();}
document.querySelector('#open-proposal').addEventListener('click',setupProposal);
document.querySelector('#open-proposal-bottom').addEventListener('click',setupProposal);
document.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
for(const dialog of [bookingDialog,proposalDialog])dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close();});
