import {modules,phases,readingsFor,primaryFor,toolsFor,moduleCount,moduleNumber,moduleFor,nextModule,lessonSheets,courseToolLabels,STAGES,courseFor,freeModules} from './course-data.js';
import {pricing,money} from './pricing-config.js';
const courseLabel=p=>`Course ${p.number} · ${p.name}`;
import {softwareProducts,resourceManifest,previewToolSlugs} from './products.js';
import {hasToolAccess} from './tool-access.js';
import {readState,mutateState,emptyState,lessonKey,stats,isFilled,invalidate,escapeHTML as e,download,STORAGE_KEY,validateState,FIRST_LESSON} from './learning-store.js';
const root=document.querySelector('#learning-root');
let state;let storageError='';try{state=readState();}catch(err){state=emptyState();storageError='Saved work could not be loaded. Storage may be unavailable or the saved file may be damaged. Your existing data has not been overwritten. You can export this session or restore a backup from Your Organisation.';}
const urlFor=(m,l)=>`learn.html?module=${m.id}&lesson=${l.id}`;
const lessonNo=(m,l)=>`${m.id}.${m.lessons.indexOf(l)+1}`;
const toolName=p=>courseToolLabels[p.slug]||p.name;
const toolsBySlug=slugs=>slugs.map(slug=>softwareProducts.find(p=>p.slug===slug)).filter(Boolean);
const toolHref=p=>previewToolSlugs.includes(p.slug)&&p.launchUrl?p.launchUrl:`software-${p.slug}.html`;
const statusText=()=>storageError||'Drafts save on this browser as you type. Export a backup before changing device or clearing browser data.';
function save(change){try{state=mutateState(change);storageError='';return true;}catch(err){change(state);storageError='Could not save on this browser. Your latest edits remain in this session; export a backup before leaving.';return false;}}
function status(message,error=false){refreshProgress();const el=document.querySelector('#save-status');if(el){el.textContent=message;el.classList.toggle('error',error);}}
const currentModule=()=>moduleFor(new URLSearchParams(location.search).get('module'))||modules[0];

function refreshProgress(){const all=stats(state);const p=document.querySelector('#course-progress');if(p)p.textContent=`${all.done} of ${all.total} lessons complete`;const courseBar=document.querySelector('progress[aria-label="Course progress"]');if(courseBar)courseBar.value=all.percent;const current=currentModule();const active=current.lessons.findIndex(l=>l.id===new URLSearchParams(location.search).get('lesson'));const position=document.querySelector('.lesson-meta span');if(position)position.textContent=`Module ${moduleNumber(current)} of ${moduleCount-1} · Lesson ${Math.max(active,0)+1} of ${current.lessons.length} · Course ${all.percent}%`;const modBar=document.querySelector('progress[aria-label="Module progress"]');if(modBar)modBar.value=stats(state,current).percent;const text=document.querySelector('#module-progress-text');if(text)text.textContent=`Module progress: ${stats(state,current).done}/${current.lessons.length} complete`;document.querySelectorAll('.module-nav').forEach(nav=>{const m=moduleFor(nav.dataset.module);if(!m)return;nav.querySelector('summary .subtle').textContent=`${stats(state,m).done}/${m.lessons.length}`;nav.querySelectorAll('a[data-lesson]').forEach(a=>{const l=m.lessons.find(x=>x.id===a.dataset.lesson);const s=a.querySelector('.nav-status');const done=state.completed[lessonKey(m,l)];s.textContent=done?'✓':'○';s.setAttribute('aria-label',done?'Completed':'Incomplete');});});}

// ---------- navigation ----------
function lessonLinks(x,m,l){let part='';return x.lessons.map(y=>{const heading=y.part&&y.part!==part?`<li class="part-label">${e(y.part)}</li>`:'';part=y.part||part;const done=state.completed[lessonKey(x,y)];return `${heading}<li><a data-lesson="${e(y.id)}" href="${urlFor(x,y)}" ${x.id===m.id&&y.id===l.id?'aria-current="step"':''}><span class="nav-status" aria-label="${done?'Completed':'Incomplete'}">${done?'✓':'○'}</span>${lessonNo(x,y)} ${e(y.title)}</a></li>`;}).join('');}
function nav(m,l){return `<details class="course-sidebar" ${matchMedia('(min-width:761px)').matches?'open':''}><summary>Planning System · course contents</summary><div class="sidebar-inner"><a href="organisation.html">Your Organisation →</a><p class="subtle" id="course-progress">${stats(state).done} of ${stats(state).total} lessons complete</p><progress aria-label="Course progress" max="100" value="${stats(state).percent}"></progress>${phases.map(p=>`<p class="phase-label"><a href="course-${p.id}.html">${e(courseLabel(p))}</a></p>${modules.filter(x=>x.phase===p.name).map(x=>`<details class="module-nav" data-module="${x.id}" ${x.id===m.id?'open':''}><summary>${moduleNumber(x)}. ${e(x.title)} <span class="subtle">${stats(state,x).done}/${x.lessons.length}</span></summary><ol>${lessonLinks(x,m,l)}</ol></details>`).join('')}`).join('')}</div></details>`;}

// ---------- outputs ----------
function output(m,links=true){return m.lessons.filter(l=>!l.review).map(l=>`<section class="review-item"><h3>${lessonNo(m,l)} ${e(l.title)}</h3>${(l.fields||[]).map(f=>`<h4>${e(f.label)}</h4><div class="output-value">${e(state.answers[lessonKey(m,l)]?.[f.key]||'Not yet drafted')}</div>`).join('')}${l.id==='timeline'?timeline():''}${links?`<a class="edit" href="${urlFor(m,l)}">Edit ${e(l.title)} →</a>`:''}</section>`).join('');}
function orgChart(){const text=state.answers['3.structure']?.structure||'';const rows=text.split('\n').map(line=>line.split('|').map(x=>x.trim())).filter(row=>row[0]);return rows.length?'<h2>Your reporting map</h2><p class="subtle">Each role shows its stated reporting line. Confirm these relationships with your team.</p><div class="org-chart">'+rows.map(([role,parent,responsibility])=>'<div class="org-node"><b>'+e(role)+'</b><small>Reports to: '+e(parent||'Not specified')+'</small><p>'+e(responsibility||'Add a responsibility in the structure lesson.')+'</p></div>').join('')+'</div>':'';}
function pathway(m){const get=id=>{const l=m.lessons.find(l=>l.id===id);return state.answers[lessonKey(m,l)]?.[l.fields[0].key]||'Not yet drafted';};return `<h2>Your change pathway</h2><p>Read forwards, then test the assumptions behind each connection.</p><div class="pathway">${[['inputs','1. Inputs'],['activities','2. Activities'],['outputs','3. Outputs'],['outcomes','4. Outcomes'],['impact','5. Impact'],['assumptions','Conditions to test']].map(([id,label])=>`<div><b>${label}</b><p>${e(get(id))}</p></div>`).join('')}</div>`;}
const special=m=>m.slug==='theory-of-change'?pathway(m):m.slug==='structure-governance'?orgChart():'';
function context(m){return m.uses.length?`<details class="context-panel"><summary>Use your earlier course work</summary><p>These are your saved course answers. They are shown here for reference; changes stay in the original lesson. Separate software products do not share this data.</p>${m.uses.map(id=>{const x=moduleFor(id);return `<details><summary>Module ${moduleNumber(x)} · ${e(x.output)}</summary>${output(x)}</details>`;}).join('')}</details>`:'';}

// ---------- the three learning assets: video, information, Excel ----------
function embed(url,title){if(!url)return '';const yt=url.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([\w-]{6,})/);const vimeo=url.match(/vimeo\.com\/(?:video\/)?(\d+)/);if(yt)return `<iframe src="https://www.youtube-nocookie.com/embed/${e(yt[1])}" title="${e(title)}" loading="lazy" allow="accelerometer; encrypted-media; picture-in-picture" allowfullscreen></iframe>`;if(vimeo)return `<iframe src="https://player.vimeo.com/video/${e(vimeo[1])}" title="${e(title)}" loading="lazy" allow="fullscreen; picture-in-picture" allowfullscreen></iframe>`;if(/^https:\/\/.+\.(mp4|webm)(\?.*)?$/i.test(url)||/^assets\/.+\.(mp4|webm)$/i.test(url))return `<video controls preload="metadata" src="${e(url)}"><track kind="captions"></video>`;return '';}
function videoSlot(url,title,label){const player=embed(url,title);return `<div class="video-slot ${player?'has-video':''}">${player||`<div class="video-placeholder" role="img" aria-label="${e(label)} — video coming soon"><span class="play-icon" aria-hidden="true">▶</span><b>${e(label)}</b><small>Video coming soon. The written lesson below covers everything you need.</small></div>`}</div>`;}
function assetStrip(m,l){const r=readingsFor(m.id,l.id);const tile=r.length?`<a href="#${r[0].anchor}" class="asset-resource"><b>${r.length>1?`Resources · ${r.length}`:'Resource'}</b><span>${e(r[0].title)}${r.length>1?` · +${r.length-1} more`:''}</span></a>`:'';return `<nav class="lesson-assets${r.length?' has-resource':''}" aria-label="This lesson includes"><a href="#watch"><b>Watch</b><span>Short video</span></a><a href="#read"><b>Read</b><span>Information &amp; examples</span></a><a href="#apply"><b>Apply</b><span>Guided exercise</span></a>${tile}<a href="#excel"><b>Excel</b><span>${e(lessonSheets(l).join(' · ')||'Module workbook')}</span></a></nav>`;}
function stageArc(l){return `<ol class="stage-arc" aria-label="Where this lesson sits: understand, design, implement, manage, review">${STAGES.map(s=>`<li class="${s===l.stage?'current':''}" ${s===l.stage?'aria-current="step"':''}>${s}</li>`).join('')}</ol>`;}
function workbookFor(m){return resourceManifest.find(r=>r.module===m.id);}
function workbookButton(m){const r=workbookFor(m);return r&&r.status==='available'&&r.objectKey?`<a class="button" href="resources.html#module-${m.id}">Download ${e(m.workbook.file)} ↓</a>`:`<span class="button ghost disabled" aria-disabled="true">${e(m.workbook.file)} · being prepared</span>`;}
function excelPanel(m,l){const sheets=lessonSheets(l);const tools=toolsBySlug(l.tools);return `<section class="learning-step excel-panel" id="excel"><span class="eyebrow">Excel</span><h2>Work on this in Excel</h2><p>This lesson uses the <b>${e(sheets.join('</b>, <b>'))}</b> ${sheets.length>1?'sheets':'sheet'} in your <b>${e(m.workbook.title)}</b>. Fill it in offline, share it with colleagues or keep a version history. The workbook is included with the course at no extra cost.</p><div class="toolbar">${workbookButton(m)}<a class="plain-button" href="resources.html#module-${m.id}">About this workbook</a></div>${tools.length?`<p class="subtle">These sheets use the same columns as ${tools.map(p=>`<b>${e(toolName(p))}</b>`).join(' and ')}, so you can import the workbook into the tool later without retyping.</p>`:''}</section>`;}

// ---------- tools ----------
function toolEvidence(m,l){const item=readingsFor(m.id,l.id).find(i=>i.role==='Core resource')||readingsFor(m.id,l.id)[0];return item?`<p class="tool-evidence"><b>Evidence behind this step:</b> <a href="#${item.anchor}">${e(item.title)}</a> · ${e(item.organisation)}. Check your record against it before you share it.</p>`:'';}
function toolPanel(m,l){if(m.promo?.lesson===l.id&&!hasToolAccess())return '';const tools=toolsBySlug(toolsFor(m.id,l.id));if(!tools.length)return '';return `<section class="learning-step tool-link" aria-label="Build it in the tool"><span class="eyebrow">Build it in the tool</span><h2>${tools.length===1?`Take this into ${e(toolName(tools[0]))}`:'Take this into the Impact Tools'}</h2><p>${l.review?'Your module output is ready to become a live, shareable record.':'When your draft is ready, turn it into a live record you can update, review and export to Excel.'} Nothing is copied automatically — import this module’s workbook or re-enter your work.</p>${toolEvidence(m,l)}<ul class="tool-link-list">${tools.map(p=>`<li><a class="button ghost" href="${toolHref(p)}">${e(toolName(p))} →</a><span class="subtle">${e(p.description)}</span></li>`).join('')}</ul></section>`;}
// One box per module, on the lesson where the tools help most, for learners who only bought the course.
function promoBox(m,l){const promo=m.promo;if(!promo||promo.lesson!==l.id)return '';const tools=toolsBySlug(promo.tools);if(hasToolAccess())return `<p class="tools-access-note">You have Impact Tools access. Continue this work in ${tools.map(p=>`<a href="${toolHref(p)}">${e(toolName(p))}</a>`).join(', ')}.</p>`;const demo=promo.demo?embed(promo.demo,`${promo.headline} demo`):'';return `<aside class="tools-promo compact" aria-labelledby="promo-${m.id}"><div class="tools-promo-copy"><span class="eyebrow">Impact Tools · optional subscription</span><h2 id="promo-${m.id}">${e(promo.headline)}</h2><p>${e(promo.pitch)}</p><ul class="promo-tools">${tools.map(p=>`<li><b>${e(toolName(p))}</b><span>${e(p.description)}</span></li>`).join('')}</ul><div class="toolbar"><a class="button" href="pricing.html#software">See subscription options</a><a class="button ghost" href="${toolHref(tools[0])}">Try ${e(toolName(tools[0]))} →</a></div><p class="subtle">You do not need the tools to complete this course. Your workbook imports straight into them if you subscribe later.</p></div><div class="demo-slot">${demo?`<div class="video-slot has-video">${demo}</div>`:`<div class="video-placeholder demo" role="img" aria-label="Tool demo coming soon"><span class="play-icon" aria-hidden="true">▶</span><b>See ${e(toolName(tools[0]))} in action</b><small>Demo video coming soon.</small></div>`}</div></aside>`;}

// ---------- lesson body ----------
function timeline(){if(!state.tasks.length)return '<p>No scheduled tasks yet.</p>';const valid=state.tasks.filter(t=>t.start&&t.end&&Number.isFinite(Date.parse(t.start))&&Number.isFinite(Date.parse(t.end))&&t.end>=t.start);if(!valid.length)return '<p>Add valid start and finish dates to see the timeline.</p>';const first=Math.min(...valid.map(t=>Date.parse(t.start))),last=Math.max(...valid.map(t=>Date.parse(t.end))),day=86400000,range=Math.max(day,last-first+day);return `<div class="timeline"><p class="subtle">${new Date(first).toISOString().slice(0,10)} → ${new Date(last).toISOString().slice(0,10)} · Tasks do not reschedule automatically.</p>${valid.map(t=>`<div class="timeline-row"><span>${e(t.title)}<br><small>${e(t.owner)}</small></span><div><div class="timeline-track" aria-hidden="true"><div class="timeline-bar" style="left:${(Date.parse(t.start)-first)/range*100}%;width:${(Date.parse(t.end)-Date.parse(t.start)+day)/range*100}%"></div></div><small>${e(t.start)} → ${e(t.end)}</small></div></div>`).join('')}</div>`;}
function taskEditor(){return `<h3>Course work plan</h3><p class="field-hint">Add your initial tasks. Dates are calendar dates; owners and dependencies need your review.</p><ul class="task-list">${state.tasks.map((t,i)=>`<li class="task-row"><div class="task-fields">${[['title','Task','text'],['owner','Owner','text'],['start','Start','date'],['end','Finish','date']].map(([key,label,type])=>`<label>${label}<input type="${type}" required data-task="${i}" data-field="${key}" value="${e(t[key])}"></label>`).join('')}</div><button class="plain-button" type="button" data-remove-task="${i}">Remove this draft task</button></li>`).join('')}</ul><button class="button ghost" type="button" id="add-task">Add task</button><div id="timeline-preview">${timeline()}</div>`;}
function reviewBody(m,l){const pending=m.lessons.filter(x=>!x.review&&!state.completed[lessonKey(m,x)]);return `<p>Review the work you have built across this module. Edit an answer at its source and this output will update automatically.</p>${special(m)}${output(m)}${pending.length?`<div class="reflection"><h3>Before completing this module</h3><p>Save and complete these lessons:</p><ul>${pending.map(x=>`<li><a href="${urlFor(m,x)}">${lessonNo(m,x)} ${e(x.title)}</a></li>`).join('')}</ul></div>`:`<form id="review-form"><label class="check-label"><input type="checkbox" required>I have reviewed this output, checked the assumptions and identified what still needs testing.</label><button class="button" type="submit">${state.completed[lessonKey(m,l)]?'Continue →':'Complete module & continue →'}</button></form>`}<div class="toolbar"><button class="button ghost" id="export-module">Download module output</button><a href="organisation.html">Review all outputs →</a></div>`;}
function lessonBody(m,l){return `<section class="learning-step" id="read"><span class="eyebrow">Read</span><h2>${e(l.title)}</h2>${readWithResources(m,l)}</section><section class="learning-step"><span class="eyebrow">See an example</span><p class="subtle">Fictional examples for learning; these are not claims about real organisations.</p><div class="example-grid"><div class="example weak"><b>Too vague</b><p>${e(l.weak)}</p></div><div class="example strong"><b>More useful</b><p>${e(l.strong)}</p></div></div><p><b>Why this works:</b> ${e(l.why)}</p></section><section class="reflection"><span class="eyebrow">Reflect</span><p>${e(l.reflect)}</p></section><section class="learning-step exercise" id="apply"><span class="eyebrow">Apply it to your organisation</span><h2>Your exercise</h2><p>${e(l.exercise)}</p>${applyResource(m,l)}<form id="lesson-form">${l.fields.map(f=>`<label for="${f.key}">${e(f.label)}</label><small class="field-hint" id="hint-${f.key}">${e(f.hint)}</small><textarea required maxlength="20000" id="${f.key}" name="${f.key}" aria-describedby="hint-${f.key}">${e(state.answers[lessonKey(m,l)]?.[f.key]||'')}</textarea>`).join('')}${l.id==='timeline'?`<div id="task-editor">${taskEditor()}</div>`:''}<label class="check-label"><input id="quality-check" type="checkbox" required>${e(l.check)}</label><p class="subtle">Complete the fields and check your work before marking this lesson complete. You can return and revise it.</p><button type="submit" class="button">Save & continue →</button></form></section>${excelPanel(m,l)}`;}
// Resources sit inside the Read step, straight after the paragraph whose concept they support (item.after),
// explain why they were chosen and what to look for, and link to their Evidence Library entry.
const libraryHref=item=>{const home=primaryFor(item)||item;return `reading-library.html?module=${home.module}#${home.anchor}`;};
function accessNote(item){return item.access&&item.access!=='Free'?`<span class="explore-access">${e(item.access)}</span>`:'';}
function resourceCallout(m,l,item){const home=item.crossRef?primaryFor(item):null;const homeLesson=home?moduleFor(String(home.module))?.lessons.find(x=>`${home.module}.${x.id}`===home.lesson):null;
 return `<aside class="explore-further role-${item.role.split(' ')[0].toLowerCase()}" id="${item.anchor}" aria-label="Explore further: ${e(item.title)}"><div class="explore-head"><span class="eyebrow">Explore further</span><span class="explore-role">${e(item.role)}</span></div><h3><a href="${item.url}" target="_blank" rel="noopener">${e(item.title)} ↗</a></h3><p class="explore-source">${e(item.organisation)} · ${e(item.type)}${item.year&&!/^n\.?d/i.test(item.year)?` · ${e(item.year)}`:''}${item.region&&item.region!=='Global'?` · ${e(item.region)}`:''} ${accessNote(item)}</p><p><b>Why we chose it:</b> ${e(item.why)}</p><p><b>What to look for:</b> ${e(item.focus)}</p><p class="resource-use"><b>Use it in this lesson →</b> ${e(item.use)}</p>${home&&homeLesson?`<p class="explore-home">Main home: <a href="${urlFor(moduleFor(String(home.module)),homeLesson)}#${home.anchor}">Lesson ${lessonNo(moduleFor(String(home.module)),homeLesson)} ${e(homeLesson.title)}</a></p>`:''}<div class="resource-actions"><a href="${item.url}" target="_blank" rel="noopener">Open resource ↗</a>${item.downloadUrl?`<a href="${item.downloadUrl}" target="_blank" rel="noopener">Download PDF ↓</a>`:''}<a href="${libraryHref(item)}">See it in the Evidence Library →</a></div></aside>`;}
function readWithResources(m,l){const items=readingsFor(m.id,l.id);const last=l.learn.length-1;return l.learn.map((p,i)=>`<p>${e(p)}</p>${items.filter(item=>Math.min(Number.isInteger(item.after)?item.after:last,last)===i).map(item=>resourceCallout(m,l,item)).join('')}`).join('')+(items.length?`<p class="explore-more"><a href="${items.some(i=>!i.crossRef)?`reading-library.html?module=${m.id}#m${m.id}-${l.id}`:libraryHref(items[0])}">This lesson’s evidence in the Evidence Library →</a></p>`:'');}
// Practical guides stay in view while the learner applies the concept; fall back to the core resource.
function applyResource(m,l){const items=readingsFor(m.id,l.id);const pick=items.filter(i=>i.role==='Practical guide');const list=(pick.length?pick:items.filter(i=>i.role==='Core resource')).slice(0,2);return list.length?`<div class="apply-resource"><b>Keep ${list.length>1?'these':'this'} open while you work:</b><ul>${list.map(item=>`<li><a href="${item.url}" target="_blank" rel="noopener">${e(item.title)} ↗</a> <span class="subtle">· ${e(item.organisation)} · <a href="#${item.anchor}">why it helps ↑</a></span></li>`).join('')}</ul></div>`:'';}
function courseTag(m){const p=courseFor(m),c=pricing.courses.find(x=>x.id===p.id);return `<p class="course-tag">${freeModules.includes(m.id)?'<b>Free module</b> · open to everyone.':`This module is part of <a href="course-${p.id}.html"><b>${e(courseLabel(p))}</b></a> · ${money(c.price)}, or all five courses for ${money(pricing.course.launch)}.`}</p>`;}
function moduleOpening(m){return `<section class="module-opening"><div><p>${e(m.intro)}</p><div class="reflection"><b>You will create: ${e(m.output)}</b><p>About ${Math.round(m.lessons.reduce((n,l)=>n+l.minutes,0)/6)/10} hours including exercises. Each lesson has a short video, the written explanation and examples, a guided exercise and its sheet in the ${e(m.workbook.title)}.</p></div></div><div><span class="eyebrow">Module introduction</span>${videoSlot(m.video,`Module ${moduleNumber(m)} introduction`,`Module ${moduleNumber(m)} introduction`)}<div class="toolbar">${workbookButton(m)}</div></div></section>${courseTag(m)}`;}

function renderLesson(){const q=new URLSearchParams(location.search);const m=moduleFor(q.get('module'))||modules[0];const l=m.lessons.find(l=>l.id===q.get('lesson'))||m.lessons[0];const index=m.lessons.indexOf(l),key=lessonKey(m,l);document.title=`${lessonNo(m,l)} ${l.title} | Method into Impact`;save(s=>{s.lastLesson=key;});const next=index<m.lessons.length-1?m.lessons[index+1]:null,nextMod=nextModule(m);
 root.innerHTML=`<div class="workspace"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="courses.html">Courses</a><span>›</span><a href="planning-system.html">Planning System</a><span>›</span><a href="${m.slug}.html">Module ${moduleNumber(m)}</a></nav><div class="course-layout">${nav(m,l)}<article class="lesson-content" id="lesson"><div class="lesson-meta"><span>Module ${moduleNumber(m)} of ${moduleCount-1} · Lesson ${index+1} of ${m.lessons.length} · Course ${stats(state).percent}%</span><span>About ${l.minutes} minutes</span></div><p class="subtle" id="module-progress-text">Module progress: ${stats(state,m).done}/${m.lessons.length} complete</p><progress aria-label="Module progress" max="100" value="${stats(state,m).percent}"></progress><span class="eyebrow">${e(courseLabel(courseFor(m)))} · ${e(m.title)}${l.part?` · ${e(l.part)}`:''}</span><h1>${lessonNo(m,l)} ${e(l.title)}</h1>${stageArc(l)}${index===0?moduleOpening(m):''}<p class="saved-status ${storageError?'error':''}" id="save-status" role="status">${e(statusText())}</p><div class="toolbar"><button class="plain-button" id="backup-session">Export course backup</button></div>${l.review?'':assetStrip(m,l)}<section class="learning-step watch" id="watch"><span class="eyebrow">Watch</span>${videoSlot(l.video,l.title,`${lessonNo(m,l)} ${l.title}`)}</section>${context(m)}${l.review?reviewBody(m,l):lessonBody(m,l)}${promoBox(m,l)}${toolPanel(m,l)}<div class="lesson-actions">${index>0?`<a href="${urlFor(m,m.lessons[index-1])}">← Previous lesson</a>`:`<a href="${m.slug}.html">← Module overview</a>`}${next?`<a href="${urlFor(m,next)}">Next: ${e(next.title)} →</a>`:nextMod?`<a href="${urlFor(nextMod,nextMod.lessons[0])}">Next module: ${e(nextMod.title)} →</a>`:'<a href="organisation.html">Your Organisation →</a>'}</div></article></div></div>`;
 if(location.hash){const target=document.getElementById(decodeURIComponent(location.hash.slice(1)));if(target){target.classList.add('is-target');requestAnimationFrame(()=>target.scrollIntoView({block:'start'}));}}
 document.querySelector('#backup-session').onclick=()=>download('planning-system-backup.json',JSON.stringify(state,null,2),'application/json');
 const continueToNext=()=>{if(next)location.href=urlFor(m,next);else if(nextMod)location.href=urlFor(nextMod,nextMod.lessons[0]);else location.href='organisation.html?completed=1';};
 document.querySelector('#lesson-form')?.addEventListener('input',event=>{const field=l.fields.find(f=>f.key===event.target.name);if(!field)return;const value=event.target.value;const ok=save(s=>{s.answers[key]||={};s.answers[key][field.key]=value;invalidate(s,m,l);});document.querySelector('#quality-check').checked=false;status(ok?'Draft saved on this browser. Complete the exercise to update progress.':storageError,!ok);});
 document.querySelector('#lesson-form')?.addEventListener('submit',event=>{event.preventDefault();if(!isFilled(state,m,l)){status('Complete every field and check that task finish dates are on or after start dates.',true);return;}if(save(s=>{s.completed[key]=true;}))continueToNext();else status(storageError,true);});
 document.querySelector('#review-form')?.addEventListener('submit',event=>{event.preventDefault();if(save(s=>{s.completed[key]=true;}))continueToNext();else status(storageError,true);});
 document.querySelector('#export-module')?.addEventListener('click',()=>download(`module-${moduleNumber(m)}-${m.slug}.md`,markdown([m])));
 bindTasks(m,l);
}
function bindTasks(m,l){const editor=document.querySelector('#task-editor');if(!editor)return;editor.addEventListener('input',event=>{const index=Number(event.target.dataset.task),field=event.target.dataset.field;if(!Number.isInteger(index)||!['title','owner','start','end'].includes(field))return;const value=event.target.value;const ok=save(s=>{if(s.tasks[index])s.tasks[index][field]=value;invalidate(s,m,l);});document.querySelector('#quality-check').checked=false;status(ok?'Work plan draft saved.':storageError,!ok);document.querySelector('#timeline-preview').innerHTML=timeline();});editor.addEventListener('click',event=>{if(event.target.id==='add-task'){if(state.tasks.length>=200){status('This course planner supports up to 200 tasks.',true);return;}const ok=save(s=>{s.tasks.push({id:`task-${Date.now()}`,title:'',owner:'',start:'',end:''});invalidate(s,m,l);});editor.innerHTML=taskEditor();status(ok?'Task added.':storageError,!ok);}if(event.target.hasAttribute('data-remove-task')){const index=Number(event.target.dataset.removeTask);const removed=state.tasks[index];const ok=save(s=>{s.tasks.splice(index,1);invalidate(s,m,l);});editor.innerHTML=taskEditor();status(ok?'Draft task removed. Use Undo if needed.':storageError,!ok);const undo=document.createElement('button');undo.type='button';undo.className='plain-button';undo.textContent='Undo removed task';undo.onclick=()=>{save(s=>{s.tasks.splice(index,0,removed);});editor.innerHTML=taskEditor();undo.remove();};document.querySelector('#save-status').append(undo);}});}
function markdown(selected=modules){return `# Your Organisation\n\nPlanning System course work · ${new Date().toISOString().slice(0,10)}\n\n`+selected.map(m=>`## Module ${moduleNumber(m)}. ${m.output}\n\nStatus: ${stats(state,m).done}/${m.lessons.length} lessons complete\n\n`+m.lessons.filter(l=>!l.review).map(l=>`### ${lessonNo(m,l)} ${l.title}\n\n`+l.fields.map(f=>`**${f.label}**\n\n${state.answers[lessonKey(m,l)]?.[f.key]||'Not yet drafted'}\n\n`).join('')+(l.id==='timeline'?state.tasks.map(t=>`- ${t.title} | ${t.owner} | ${t.start} → ${t.end}`).join('\n')+'\n\n':'')).join('')).join('\n');}
function renderOrganisation(){const progress=stats(state);root.innerHTML=`<div class="output-pack"><nav class="breadcrumbs"><a href="planning-system.html">Planning System</a><span>› Your Organisation</span></nav><span class="eyebrow">Your course strategy pack</span><h1>Your Organisation</h1><p>Each lesson adds to an output you can review, revise and use. This pack brings together your course work; it does not connect separate software products.</p><p><b>${progress.done} of ${progress.total} lessons complete · ${progress.percent}%</b></p><progress aria-label="Planning System progress" value="${progress.percent}" max="100"></progress><p id="save-status" role="status" class="saved-status ${storageError?'error':''}">${e(statusText())}</p><div class="toolbar no-print"><a class="button" href="${resumeURL()}">Continue learning →</a><button class="button ghost" id="download-pack">Download strategy pack</button><button class="plain-button" id="print-pack">Print / save PDF</button></div><details class="no-print resource-panel"><summary>Back up or restore your work</summary><p>A backup includes your course answers and progress. Import replaces this browser’s current course work after you review the file. Backups from the earlier eight-module course are moved to the new lessons automatically. It never grants paid access.</p><button class="button ghost" id="backup">Download backup</button><label class="field-label" for="restore">Choose a backup to review</label><input type="file" id="restore" accept=".json,application/json"><p id="import-status" role="status"></p></details>${phases.map(p=>`<h2 class="phase-heading">${e(courseLabel(p))} <small>${e(p.summary)}</small></h2>${modules.filter(m=>m.phase===p.name).map(m=>`<details class="output-section"><summary><span>Module ${moduleNumber(m)} · ${e(m.output)}</span><small>${stats(state,m).done}/${m.lessons.length} complete${stats(state,m).done===m.lessons.length?' · ✓ Completed':''}</small></summary><section><div class="section-head"><div><span class="eyebrow">Module ${moduleNumber(m)} · ${stats(state,m).done===m.lessons.length?'Completed':stats(state,m).done?'In progress':'Not completed'}</span><h2>${e(m.output)}</h2></div></div><p class="subtle">${stats(state,m).done}/${m.lessons.length} lessons complete</p>${special(m)}${output(m)}</section></details>`).join('')}`).join('')}</div><dialog class="import-dialog" id="import-dialog"><h2>Restore course backup?</h2><p id="import-summary"></p><p>This replaces your current course answers and progress on this browser. Download a backup first if you want to keep both versions.</p><div class="toolbar"><button class="button ghost" id="keep-backup">Back up current work</button><button class="button" id="confirm-import">Restore this file</button><button class="plain-button" id="cancel-import">Cancel</button></div></dialog>`;
 document.querySelector('#download-pack').onclick=()=>download('organisation-strategy-pack.md',markdown());document.querySelector('#print-pack').onclick=()=>{document.querySelectorAll('.output-section').forEach(d=>d.open=true);window.print();};const backup=()=>download('planning-system-backup.json',JSON.stringify(state,null,2),'application/json');document.querySelector('#backup').onclick=backup;document.querySelector('#keep-backup').onclick=backup;const dialog=document.querySelector('#import-dialog');let incoming=null;document.querySelector('#cancel-import').onclick=()=>{incoming=null;dialog.close();};document.querySelector('#restore').onchange=async event=>{try{const file=event.target.files[0];if(!file)return;if(file.size>2000000)throw new Error('Choose a backup smaller than 2 MB.');incoming=validateState(JSON.parse(await file.text()));document.querySelector('#import-summary').textContent=`This file contains ${Object.keys(incoming.answers).length} lesson drafts, ${stats(incoming).done} completed lessons and ${incoming.tasks.length} tasks.`;dialog.showModal();}catch(err){document.querySelector('#import-status').textContent=`Could not import: ${err.message}`;}};document.querySelector('#confirm-import').onclick=()=>{if(!incoming)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(incoming));state=incoming;storageError='';dialog.close();renderOrganisation();status('Backup restored on this browser.');}catch(err){document.querySelector('#import-summary').textContent='Storage is unavailable. Your existing work has not been replaced.';}};
}
export function resumeURL(){const [id,...parts]=(state.lastLesson||FIRST_LESSON).split('.');return `learn.html?module=${id}&lesson=${parts.join('.')}`;}
if(root){if(document.body.dataset.page==='organisation')renderOrganisation();else renderLesson();}
window.addEventListener('storage',event=>{if(event.key===STORAGE_KEY){status('Course work changed in another tab. Reload before continuing here so you can review the latest version.',true);document.querySelectorAll('#lesson-form input,#lesson-form textarea,#lesson-form button,#review-form input,#review-form button').forEach(b=>b.disabled=true);}});
