import {pricing} from './pricing-config.js';
export const courseProduct={id:pricing.course.productId,name:pricing.course.name,kind:'course',billing:'one_time',price:pricing.course.launch,currency:pricing.currency,status:'preview',checkout:null,resourceIds:['strategic-foundation','theory-of-change','organisation-chart','internal-systems','policies','work-plan-gantt','business-model','funding-strategy']};
// No price, trial, subscription, or bundle is inferred from a course purchase.
export const softwareProducts=[
 ['strategic-planning','Strategic Planning','Strategy','Founders keeping strategic priorities clear','Track objectives, measures and responsibility in one focused tool.',['Objective','Indicator','Owner','Deadline','Status']],
 ['theory-of-change','Theory of Change Builder','Strategy','Teams testing their impact logic','Map the changes you expect and record the assumptions behind them.',['Pathway step','Type','Expected change','Assumption','Evidence']],
 ['work-plan','Work Plan','Project management','Small teams coordinating delivery','Keep activities, owners and next actions visible.',['Activity','Owner','Due date','Status','Next action']],
 ['gantt','Gantt Tool','Project management','Project leads planning a timeline','Put tasks on a calendar and discuss sequencing and overlap.',['Task','Owner','Start','Finish','Dependency']],
 ['policy-management','Policy Management','Organisation','Teams maintaining organisational policies','Track policy owners, review dates and approval status.',['Policy','Owner','Review date','Status','Next action']],
 ['risk-register','Risk Register','Organisation','Teams reviewing delivery and organisational risks','Record risks, controls and the person responsible for the response.',['Risk','Likelihood','Impact','Control','Owner']],
 ['kpi-tracker','KPI Tracker','Monitoring','Teams checking progress against priorities','Keep performance measures and review decisions together.',['Measure','Target','Current value','Owner','Review date']],
 ['indicator-tracker','Indicator Tracker','Monitoring','Programme teams defining evidence','Record indicator definitions, data sources and collection responsibilities.',['Indicator','Definition','Data source','Frequency','Owner']],
 ['donor-mapping','Donor Mapping','Funding & relationships','Fundraisers researching relevant prospects','Compare prospects by fit and keep research evidence visible.',['Organisation','Fit','Eligibility','Research source','Next action']],
 ['funding-pipeline','Funding Pipeline','Funding & relationships','Teams following funding opportunities','Track relationship stages and distinguish opportunities from commitments.',['Opportunity','Stage','Potential amount','Confirmed amount','Next action']],
 ['partner-tracker','Partner Tracker','Funding & relationships','Teams maintaining purposeful partnerships','Keep commitments and next conversations visible without a complex CRM.',['Partner','Shared purpose','Commitment','Owner','Next action']]
].map(([slug,name,category,audience,description,fields])=>({id:`software_${slug.replaceAll('-','_')}`,slug,name,category,audience,description,fields,kind:'software',suiteIncluded:pricing.suite.toolSlugs.includes(slug),billing:['monthly','annual'],prices:{monthly:null,annual:null},currency:pricing.currency,status:'demo',trial:null,checkout:{monthly:null,annual:null},dataNamespace:`mm.software.${slug}.v1`,entitlements:[]}));
export const resourceManifest=courseProduct.resourceIds.map((id,index)=>({id,courseId:courseProduct.id,module:index+1,name:['Strategic Foundation','Theory of Change','Organisation Chart and Role Framework','Internal Systems Blueprint','Policy Register and Procedures','Work Plan and Gantt','Business Model','Funding and Partnerships'][index]+' Excel workbook',version:null,objectKey:null,status:'awaiting_owner_file',requiresEntitlement:courseProduct.id}));
