// Curated September 2026. Each resource has one primary lesson home.
// Regulatory guidance is tagged by jurisdiction in its description.
const r=(title,organisation,type,category,level,url,why,use,tags=[],downloadUrl='')=>({title,organisation,type,category,level,url,why,use,tags,downloadUrl});

export const resourcePlan={
'1.purpose':[
r('Mission and Vision Statements','Bridgespan','Guide','Start here','Essential','https://www.bridgespan.org/insights/mission-and-vision-statements','Separates an organisation’s present purpose from its desired future and shows how both guide choices.','Read before drafting your purpose statement.',['NGO','Management','Beginner']),
r('The Sustainable Development Goals','United Nations','Evidence library','Evidence & databases','Reference','https://sdgs.un.org/goals','Provides the official global goals, targets and indicators, helping you locate your purpose within a wider agenda without copying its language.','Use to check which global target your problem may contribute to.',['Development','Social enterprise','Free'])],
'1.vision':[
r('Strategic Planning in Times of Uncertainty','Bridgespan','Framework','Go deeper','Advanced','https://www.bridgespan.org/insights/nonprofit-strategy/strategic-planning-in-times-of-uncertainty-a-practical-framework-for-nonprofit-leaders','Shows how to set direction while acknowledging uncertainty and multiple possible futures.','Use when your vision depends on volatile social, political or funding conditions.',['NGO','Strategy','Management']),
r('Three Horizons Framework','International Futures Forum','Framework','Use this','Practical','https://www.iffpraxis.com/three-horizons','A visual framework for connecting today’s dominant system, emerging alternatives and the future you want to help create.','Use to discuss the transition between present reality and your vision.',['Systems change','Innovation','Social enterprise'])],
'1.mission':[
r('Strategic Planning for Nonprofits and NGOs','Bridgespan','Guide','Start here','Essential','https://www.bridgespan.org/insights/nonprofit-strategy/strategic-planning-for-nonprofits-and-ngos','Connects mission, strategic choices, priorities and resource allocation instead of treating a mission as a slogan.','Use after drafting your mission to test its strategic boundaries.',['NGO','Strategy','Beginner'])],
'1.values':[
r('Charity Ethical Principles','National Council for Voluntary Organisations','Framework','Use this','Practical','https://www.ncvo.org.uk/help-and-guidance/running-a-charity/charity-ethical-principles/','Turns ethical principles into questions about beneficiaries, leadership, staff, partners and the wider public.','Use while translating values into observable behaviours and boundaries.',['NGO','Governance','Ethics']),
r('Culture Map','Strategyzer','Tool','Go deeper','Advanced','https://www.strategyzer.com/library/the-culture-map','Maps outcomes, behaviours and enablers or blockers so teams can examine whether everyday culture matches stated values.','Use with a team after the first values draft.',['Startup','Management','Culture'])],
'1.objectives':[
r('What Makes a Good OKR?','What Matters','Guide','Use this','Practical','https://www.whatmatters.com/okrs-explained/good-example-okrs','Explains how objectives express direction and key results make progress observable, with a worked public-service example.','Use to make a small number of strategic objectives measurable.',['Startup','Management','Beginner']),
r('Applying Evaluation Criteria Thoughtfully','OECD','Guide','Official standards','Advanced','https://www.oecd.org/en/publications/applying-evaluation-criteria-thoughtfully_543e84ed-en.html','Clarifies relevance, coherence, effectiveness, efficiency, impact and sustainability, including unintended and unequal effects.','Use to challenge whether objectives are relevant and sustainable.',['Development','Evaluation','PDF'],'https://www.oecd.org/content/dam/oecd/en/publications/reports/2021/03/applying-evaluation-criteria-thoughtfully_45a54ea7/543e84ed-en.pdf')],

'2.understanding':[
r('Describe the Theory of Change','BetterEvaluation','Guide','Start here','Essential','https://www.betterevaluation.org/frameworks-guides/managers-guide-evaluation/scope-evaluation/describe-theory-change','Explains causal pathways, context, other actors, assumptions and unintended results in plain practitioner language.','Read before building your first causal pathway.',['Development','Evaluation','Beginner']),
r('Theory of Change Methodological Brief','UNICEF and BetterEvaluation','PDF','Go deeper','Advanced','https://www.betterevaluation.org/sites/default/files/Theory_of_Change_ENG.pdf','A detailed method for developing a results chain and testing it with assumptions, indicators and evidence.','Use when facilitating a full Theory of Change workshop.',['Development','NGO','PDF','Evaluation'])],
'2.problem':[
r('Start by Learning About Users and Their Needs','GOV.UK Service Manual','Guide','Use this','Practical','https://www.gov.uk/service-manual/user-research/start-by-learning-user-needs','Shows how to replace solution-led assumptions with evidence about people, tasks, barriers and context.','Use before finalising the problem statement or proposed solution.',['Management','Research','Beginner']),
r('Problem Tree Analysis','Overseas Development Institute','Toolkit','Use this','Practical','https://odi.org/en/publications/planning-tools-problem-tree-analysis/','Provides a participatory method for separating a focal problem from its causes and effects.','Use in a workshop with people affected by the issue.',['Development','NGO','Participatory'])],
'2.impact':[
r('Contribution Analysis','BetterEvaluation','Framework','Go deeper','Advanced','https://www.betterevaluation.org/methods-approaches/approaches/contribution-analysis','Helps test a credible contribution story without claiming that one organisation caused a complex long-term change alone.','Use when your impact depends on many actors or external conditions.',['Evaluation','Research','Development'])],
'2.outcomes':[
r('Outcome Mapping','BetterEvaluation','Framework','Start here','Practical','https://www.betterevaluation.org/methods-approaches/approaches/outcome-mapping','Focuses on observable changes in the behaviour, relationships and actions of people you seek to influence.','Use when outcomes concern behaviour or relationships rather than service totals.',['Evaluation','Participatory','NGO']),
r('Outcome Harvesting','BetterEvaluation','Framework','Go deeper','Advanced','https://www.betterevaluation.org/methods-approaches/approaches/outcome-harvesting','Works backwards from observed changes to verify how an intervention contributed, including unexpected outcomes.','Use when outcomes are emergent or were not fully specified in advance.',['Evaluation','Research','Complexity'])],
'2.outputs':[
r('Results-Based Management Handbook','UNICEF','Handbook','Start here','Essential','https://www.unicef.org/thailand/reports/result-based-management-handbook','Distinguishes activities, outputs, outcomes and impact and connects planning with monitoring and adaptation.','Use while checking whether each output is a deliverable within your control.',['Development','NGO','PDF','Beginner'],'https://www.unicef.org/thailand/media/3486/file/Result-based%20management%20handbook.pdf')],
'2.activities':[
r('Programme Design and Performance Management Toolkit','FCDO','Toolkit','Use this','Practical','https://www.gov.uk/government/publications/dfid-smart-rules-better-programme-delivery','Links programme design, delivery choices, risk and adaptive management in an official donor context.','Use when turning outputs into a realistic sequence of activities.',['Development','Donor','Management'])],
'2.inputs':[
r('Costing and Financing of Small-scale WASH Projects','IRC','Guide','See an example','Practical','https://www.ircwash.org/resources/costing-and-financing-small-scale-water-supply-and-sanitation-services','Shows how lifecycle costs extend beyond initial delivery and include maintenance, support and replacement.','Use as an example when identifying the full resources an activity requires.',['Development','Finance','Case study'])],
'2.assumptions':[
r('Theory of Change in Practice','USAID Learning Lab','Toolkit','Use this','Practical','https://usaidlearninglab.org/resources/theories-change','Collects practitioner guidance for articulating, testing and revising causal assumptions in context.','Use to turn hidden assumptions into questions that can be investigated.',['Development','Evaluation','Toolkit']),
r('The Magenta Book','HM Treasury','Guide','Official standards','Advanced','https://www.gov.uk/government/publications/the-magenta-book','Official UK guidance on designing and using evaluation, including theory, evidence, methods and proportionality.','Use when planning how assumptions and results will be tested.',['Evaluation','Research','Government'])],

'3.structure':[
r('Charity Governance Code','Charity Governance Code Steering Group','Standard','Official standards','Essential','https://www.charitygovernancecode.org/en','Sets principles for organisational purpose, leadership, integrity, decision making, board effectiveness, equality and openness.','Use when defining the relationship between governance and management.',['NGO','Governance','Standard']),
r('Operating Models: How Nonprofits Get from Strategy to Results','Bridgespan','Guide','Use this','Practical','https://www.bridgespan.org/insights/nonprofit-organizational-effectiveness/nonprofit-operating-models','Connects structure to strategy, capabilities, accountabilities and coordination rather than starting with an organisation chart.','Use before drawing the organisation structure.',['NGO','Management','Organisation design'])],
'3.roles':[
r('Decision-making for Charity Trustees (CC27)','Charity Commission for England and Wales','Regulatory guide','Official standards','Essential','https://www.gov.uk/government/publications/decision-making-for-charity-trustees-cc27/decision-making-for-charity-trustees','Explains lawful, informed decisions, delegation, conflicts and proportionate records for charities in England and Wales.','Use to define reserved decisions, delegation and records; adapt to local law.',['NGO','Governance','UK']),
r('DACI: A Decision-Making Framework','Atlassian','Framework','Use this','Practical','https://www.atlassian.com/team-playbook/plays/daci','Defines driver, approver, contributors and informed participants for a specific decision.','Use when one task has many stakeholders but unclear authority.',['Startup','Management','Template'])],
'3.coordination':[
r('Project Delivery Functional Standard','UK Government','Standard','Official standards','Advanced','https://www.gov.uk/government/publications/project-delivery-functional-standard','Sets accountable roles, governance, planning and control expectations across portfolios, programmes and projects.','Use to compare your coordination model with a mature delivery standard.',['Management','Government','Standard']),
r('Team Charter','Atlassian','Template','Use this','Practical','https://www.atlassian.com/team-playbook/plays/team-poster','Prompts a team to agree purpose, people, goals, measures and ways of working in a shared artefact.','Use during team formation or when coordination repeatedly breaks down.',['Startup','Template','Culture'])],
'3.onboarding':[
r('Induction Factsheet','CIPD','Guide','Start here','Essential','https://www.cipd.org/en/knowledge/factsheets/induction-factsheet/','Explains effective induction, responsibilities and the practical and social information new people need.','Use to design the first days and weeks for staff or volunteers.',['HR','Management','Beginner']),
r('Performance Management Toolkit','International Labour Organization','Toolkit','Go deeper','Practical','https://www.ilo.org/publications/tool-4-performance-management','Provides practical guidance on expectations, feedback, development and fair performance conversations.','Use after onboarding to connect roles with continuing support.',['HR','Development','Toolkit'])],

'4.systems':[
r('Designing Good Government Services','GOV.UK Service Manual','Guide','Start here','Essential','https://www.gov.uk/service-manual/design/introduction-designing-government-services','Treats a service as an end-to-end system spanning people, channels, policies, data and internal processes.','Use before selecting software or documenting workflows.',['Service design','Management','Beginner']),
r('Principles for Digital Development','Digital Impact Alliance','Principles','Official standards','Practical','https://digitalprinciples.org/principles/','A widely used set of principles for sustainable, inclusive and interoperable digital initiatives.','Use when deciding whether and how technology should support a system.',['Technology','Development','Standard'])],
'4.brand':[
r('Ethical Reporting Guidelines','UNICEF','Guide','Official standards','Essential','https://www.unicef.org/media/reporting-guidelines','Provides safeguards for consent, dignity, privacy and avoiding harm when using people’s stories and images.','Use before collecting or publishing any participant story.',['Communications','Safeguarding','Development']),
r('Brand IDEA','Stanford Social Innovation Review','Research','Go deeper','Advanced','https://ssir.org/articles/entry/the_role_of_brand_in_the_nonprofit_sector','Presents a nonprofit brand framework centred on integrity, democracy, ethics and alignment with mission.','Use when deciding what the brand should enable inside and outside the organisation.',['NGO','Brand','Research'])],
'4.communication':[
r('Identifying User Needs for Content','Office for National Statistics','Guide','Start here','Practical','https://service-manual.ons.gov.uk/content/writing-for-users/user-needs','Connects audience evidence to clear content and warns against starting with a preferred channel or message.','Use before filling in the audience and channel plan.',['Communications','Research','Beginner']),
r('Web Content Accessibility Guidelines (WCAG) 2.2','World Wide Web Consortium','Standard','Official standards','Reference','https://www.w3.org/TR/WCAG22/','The international technical standard for making web content perceivable, operable, understandable and robust.','Reference when commissioning or reviewing digital communications.',['Accessibility','Technology','Standard'])],
'4.learning':[
r('Program Evaluation Framework Action Guide','US Centers for Disease Control and Prevention','Guide','Use this','Practical','https://www.cdc.gov/mmwr/volumes/73/rr/rr7306a1.htm','Provides a current, stepwise framework linking context, questions, credible evidence, conclusions and use.','Use to build a proportionate monitoring and learning cycle.',['Evaluation','Research','Government']),
r('CLA Toolkit','USAID Learning Lab','Toolkit','Go deeper','Advanced','https://usaidlearninglab.org/cla-toolkit','Practical tools for collaborating, learning and adapting through pause-and-reflect, knowledge management and decision routines.','Use when designing how evidence will change decisions, not only reporting.',['Development','Knowledge management','Toolkit'])],

'5.priorities':[
r('Core Humanitarian Standard on Quality and Accountability','CHS Alliance, Groupe URD and Sphere','Standard','Official standards','Essential','https://www.chsalliance.org/get-support/resource/chs-revision-resources/','The current 2024 standard sets nine commitments and centres people and communities in quality, accountability and solutions.','Use to identify policy areas where your work affects people’s rights, safety and participation.',['Humanitarian','Accountability','Standard']),
r('The Essential Trustee: What You Need to Know','Charity Commission for England and Wales','Guide','Start here','Practical','https://www.gov.uk/government/publications/the-essential-trustee-what-you-need-to-know-cc3','Connects trustee duties with governance, safeguarding, financial stewardship and accountability, helping a new organisation identify priority controls.','Use to prioritise a manageable governance and policy roadmap; adapt to local law.',['NGO','Governance','UK'])],
'5.procedures':[
r('Charity Templates','Australian Charities and Not-for-profits Commission','Template library','Use this','Practical','https://www.acnc.gov.au/tools/templates','Provides model policies, procedures, action plans and governance documents that can be adapted rather than copied blindly.','Use while structuring a first usable procedure.',['NGO','Governance','Template'])],
'5.controls':[
r('Internal Financial Controls for Charities (CC8)','Charity Commission for England and Wales','Regulatory guide','Official standards','Essential','https://www.gov.uk/government/publications/internal-financial-controls-for-charities-cc8/internal-financial-controls-for-charities','Covers approvals, separation of duties, reconciliations, restricted funds, banking, training and review.','Use to design controls around real financial risks; adapt to local law.',['NGO','Finance','UK']),
r('NGO Financial Health Check','Humentum','Assessment tool','Go deeper','Practical','https://pages.humentum.org/WC-2022-08-16-Health-Check_LP-download-the-HC.html','Assesses planning, budgeting, accounting systems, controls, staffing, grants management and reporting and points to areas needing attention.','Use when establishing or reviewing a complete finance system beyond individual controls.',['NGO','Finance','Interactive tool'])],
'5.risk':[
r('Charities and Risk Management (CC26)','Charity Commission for England and Wales','Regulatory guide','Start here','Essential','https://www.gov.uk/government/publications/charities-and-risk-management-cc26/charities-and-risk-management-cc26','A risk-based cycle for identifying, assessing, responding to and reviewing organisational risks.','Use to build the risk register and assign ownership.',['NGO','Risk','UK']),
r('Sphere Handbook','Sphere Association','Standard','Official standards','Reference','https://spherestandards.org/handbook/','Combines the Humanitarian Charter, protection principles, CHS and minimum technical standards for humanitarian response.','Reference when your programmes operate in humanitarian contexts.',['Humanitarian','Safeguarding','Standard']),
r('Getting Started with Data Protection','UK Information Commissioner’s Office','Guide','Use this','Practical','https://ico.org.uk/for-organisations/advice-for-small-organisations/getting-started-with-gdpr/getting-started-with-data-protection/','A practical sequence for identifying personal data, purpose, lawful basis, security, retention and accountability.','Use when personal data is one of your priority risks; check local law.',['Privacy','Technology','UK'])],

'6.deliverables':[
r('Practice Standard for Work Breakdown Structures','Project Management Institute','Standard','Go deeper','Advanced','https://www.pmi.org/standards/work-breakdown-structures-third-edition','Explains how to decompose total scope into manageable, testable deliverables without confusing them with a task list.','Use when a strategic objective is too large to schedule directly.',['Project management','Standard','Management']),
r('Project DPro Guide','PM4NGOs','Guide','Start here','Practical','https://pm4ngos.org/methodologies-guides/project-dpro/','An open project-management guide created for development and humanitarian organisations, covering identification through closure.','Use as the main NGO-oriented delivery reference.',['Development','Project management','PDF'])],
'6.ownership':[
r('Capacity Assessment Tool','UNDP','Toolkit','Use this','Practical','https://www.undp.org/publications/undp-capacity-assessment-methodology','Helps examine institutional arrangements, leadership, knowledge and accountability before assigning delivery expectations.','Use to test whether an owner has the authority and capacity required.',['Development','Management','Toolkit'])],
'6.dependencies':[
r('The Scrum Guide','Ken Schwaber and Jeff Sutherland','Framework','Go deeper','Advanced','https://scrumguides.org/scrum-guide.html','Defines an iterative approach for complex work using short cycles, transparent backlogs, reviews and adaptation.','Use when dependencies and uncertainty make a fixed long-range plan unreliable.',['Startup','Agile','Project management'])],
'6.timeline':[
r('Gantt Project Planner Template','Microsoft','Template','Use this','Practical','https://create.microsoft.com/en-us/template/gantt-project-planner-c1b2b2de-5c17-4a1a-b3f0-0f5c1b38c4b8','A downloadable spreadsheet structure for tasks, dates, duration and timeline visualisation.','Use after defining deliverables, owners and dependencies.',['Template','Project management','Startup'])],

'7.value':[
r('Value Proposition Canvas','Strategyzer','Framework','Start here','Essential','https://www.strategyzer.com/library/the-value-proposition-canvas','Connects an offer to evidence about a defined customer or beneficiary segment’s jobs, pains and gains.','Use before claiming that an audience values your proposed offer.',['Startup','Social enterprise','Framework']),
r('IDEO Design Kit: The Field Guide to Human-Centered Design','IDEO.org','Toolkit','Use this','Practical','https://www.designkit.org/resources/1.html','Provides 57 field methods for interviewing, synthesis, prototyping and learning with communities, plus social-sector examples.','Use when researching value with people rather than for them.',['Social enterprise','Research','Toolkit'])],
'7.delivery':[
r('Business Model Canvas','Strategyzer','Framework','Use this','Practical','https://www.strategyzer.com/library/the-business-model-canvas','Maps value, customers, channels, relationships, partners, activities, resources, costs and revenues as connected hypotheses.','Use to see how the whole delivery model fits together.',['Startup','Social enterprise','Framework']),
r('Social Business Model Canvas','Social Innovation Lab','Template','See an example','Practical','https://socialbusinessmodelcanvas.swarthmore.edu/','Adapts business-model thinking to social value, beneficiaries, customers, surplus and impact.','Use when beneficiaries and paying customers are different groups.',['Social enterprise','Template','Impact'])],
'7.economics':[
r('Write a Business Plan','GOV.UK','Guide','Start here','Practical','https://www.gov.uk/write-business-plan','Introduces objectives, market, operations and financial forecasts and provides a business-plan template.','Use to connect the model to operational and financial assumptions.',['Startup','Management','Template']),
r('IRIS+ System','Global Impact Investing Network','Database','Evidence & databases','Reference','https://iris.thegiin.org/','A catalog of generally accepted impact metrics, organised by impact themes and strategic goals.','Use to investigate suitable impact measures for a social enterprise.',['Social enterprise','Impact investing','Database'])],
'7.validation':[
r('Test Your Business Idea','Strategyzer','Guide','Use this','Practical','https://www.strategyzer.com/library/how-to-test-your-idea-start-with-the-most-critical-hypotheses','Shows how to rank desirability, feasibility and viability assumptions and run small tests against the riskiest claims.','Use to design the next low-cost experiment.',['Startup','Innovation','Practical']),
r('Lean Impact','Acumen Academy','Course','Go deeper','Advanced','https://acumenacademy.org/course/lean-impact','Applies rapid experimentation and feedback loops to social impact while keeping mission and scale in view.','Use when adapting lean methods to a purpose-led organisation.',['Social enterprise','Startup','Course'])],

'8.funding-mix':[
r('Finding Your Nonprofit’s Funding Strategy','Bridgespan','Guide','Start here','Essential','https://www.bridgespan.org/insights/nonprofit-financial-sustainability/nonprofit-funding-strategy','Uses revenue mix, funder motivations and fundraising capabilities to develop and test a focused funding strategy.','Use before deciding that diversification is automatically the best answer.',['NGO','Fundraising','Strategy']),
r('How Small and Midsize US Nonprofits Get Their Funding','Bridgespan','Research','Go deeper','Advanced','https://www.bridgespan.org/insights/how-small-and-midsize-us-nonprofits-get-their-funding','Research on funding-category focus that distinguishes resilience from dependence on a single funder.','Use to challenge assumptions about a healthy funding mix; evidence is US-specific.',['NGO','Fundraising','Research'])],
'8.prospects':[
r('Foundation Directory','Candid','Database','Evidence & databases','Reference','https://candid.org/find-us','A major funder research database available through Candid partner locations, with profiles, grants and relationships.','Use to build and qualify a prospect list where access is available.',['NGO','Fundraising','Database']),
r('Due Diligence, Monitoring and End Use of Funds','Charity Commission for England and Wales','Regulatory guide','Official standards','Practical','https://www.gov.uk/government/publications/charities-due-diligence-monitoring-and-verifying-the-end-use-of-charitable-funds/chapter-2-due-diligence-monitoring-and-end-use-of-funds','Provides “know your partner” checks and guidance on agreements, monitoring and verifying use of funds.','Use when assessing a delivery or funding partner; adapt to local law.',['NGO','Partnerships','UK'])],
'8.case':[
r('How Do I Write a Grant Proposal?','Candid Learning','Guide','Use this','Practical','https://learning.candid.org/grant-proposals/272645','Explains the core proposal elements, evidence, cover letter and supporting documents, with links to free training and funded samples.','Use while turning course outputs into a coherent case for support.',['NGO','Fundraising','Beginner']),
r('Ethics Resources and Sample Cases','Association of Fundraising Professionals','Case study','See an example','Advanced','https://afpglobal.org/resource-guides/ethics-education-sample-cases-solicitation-stewardship-philanthropic-funds','Uses cases to examine honest solicitation, donor intent, conflicts and ethical stewardship.','Use to discuss difficult funding offers and donor conditions.',['Fundraising','Ethics','Case study'])],
'8.pipeline':[
r('Charities and Fundraising (CC20)','Charity Commission for England and Wales','Regulatory guide','Official standards','Essential','https://www.gov.uk/government/publications/charity-fundraising-a-guide-to-trustee-duties-cc20/charities-and-fundraising','Covers board oversight, risk, partner arrangements, donor information and monitoring in England and Wales.','Use to define pipeline governance and stewardship controls; adapt to local law.',['NGO','Fundraising','UK']),
r('Donor Journey Mapping','Bloomerang','Template','Use this','Practical','https://bloomerang.co/blog/donor-journey-map/','A practical map of donor stages, touchpoints, questions and stewardship opportunities.','Use after defining pipeline stages to design consistent follow-up.',['Fundraising','CRM','Template'])]
};

export const readingsFor=(moduleId,lessonId)=>resourcePlan[`${moduleId}.${lessonId}`]||[];
export const resources=Object.entries(resourcePlan).flatMap(([lesson,items])=>items.map((item,index)=>({...item,id:`${lesson}-${index+1}`,lesson,module:Number(lesson.split('.')[0])})));
export const sources=resources.map(item=>[`${item.title} · ${item.organisation}`,item.url]);
