import {softwareProducts,availableToolSlugs} from './products.js';
import {escapeHTML as e,download} from './ui-utils.js';
const root=document.querySelector('#software-demo');
const product=softwareProducts.find(p=>p.slug===document.body.dataset.product);
if(root&&product&&availableToolSlugs.includes(product.slug)){
 let rows=[],error='',editing=null;
 try{const raw=JSON.parse(localStorage.getItem(product.dataNamespace)||'[]');if(!Array.isArray(raw)||raw.length>500||raw.some(x=>!x||typeof x!=='object'||product.fields.some(f=>typeof x[f]!=='string'||x[f].length>2000)))throw Error('invalid');rows=raw;}catch{error='Previous demo data could not be loaded. Export any current work before leaving; existing storage will not be overwritten.';}
 let query='';
 const persist=()=>{if(error)return false;try{localStorage.setItem(product.dataNamespace,JSON.stringify(rows));return true;}catch{error='Saving is unavailable in this browser. Export your records before leaving.';return false;}};
 function render(){root.innerHTML=`<div class="software-demo"><span class="eyebrow">Interactive product demo</span><h2>Try ${e(product.name)}</h2><p>Sample the editing workflow with your own draft records. Demo data stays in this browser, separately from your course work and every other tool. This does not activate a subscription.</p><p class="subtle">Cloud saving, collaboration, reminders and paid access are not connected in this development preview.</p><form id="demo-form">${product.fields.map((f,i)=>`<label for="demo-${i}">${e(f)}<input id="demo-${i}" name="${e(f)}" required maxlength="2000" value="${editing===null?'':e(rows[editing][f])}"></label>`).join('')}<div class="toolbar"><button class="button" type="submit">${editing===null?'Add record':'Save changes'}</button>${editing!==null?'<button class="plain-button" type="button" id="cancel-edit">Cancel edit</button>':''}</div></form><p role="status" id="demo-status" class="saved-status ${error?'error':''}">${e(error||`${rows.length} records saved on this browser`)}</p><label for="demo-search">Filter records</label><input class="demo-search" type="search" id="demo-search" placeholder="Search any field" value="${e(query)}"><div class="toolbar"><button class="button ghost" id="demo-export">Export CSV</button></div><div id="demo-rows" class="demo-rows"></div></div>`;
 renderRows();document.querySelector('#demo-form').onsubmit=event=>{event.preventDefault();const data=new FormData(event.target),row=Object.fromEntries(product.fields.map(f=>[f,String(data.get(f)||'').trim()]));if(product.fields.some(f=>!row[f])){document.querySelector('#demo-status').textContent='Complete each field with a value.';return;}if(editing===null){if(rows.length>=500){document.querySelector('#demo-status').textContent='This demo supports 500 records. Export your records to keep a copy.';return;}rows.push(row);}else rows[editing]=row;editing=null;persist();render();};document.querySelector('#cancel-edit')?.addEventListener('click',()=>{editing=null;render();});document.querySelector('#demo-search').oninput=event=>{query=event.target.value;renderRows();};document.querySelector('#demo-export').onclick=()=>{const csv=value=>{let text=String(value??'');if(/^[=+@\-\t\r]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"';};download(`${product.slug}-demo.csv`,'\uFEFF'+[product.fields,...rows.map(row=>product.fields.map(f=>row[f]))].map(row=>row.map(csv).join(',')).join('\r\n'),'text/csv;charset=utf-8');};}
 function renderRows(){const filtered=rows.map((row,i)=>({row,i})).filter(({row})=>Object.values(row).join(' ').toLowerCase().includes(query.toLowerCase()));document.querySelector('#demo-rows').innerHTML=filtered.length?filtered.map(({row,i})=>`<article class="demo-row"><h3>${e(row[product.fields[0]])}</h3><dl>${product.fields.slice(1).map(f=>`<dt>${e(f)}</dt><dd>${e(row[f])}</dd>`).join('')}</dl><button class="plain-button" data-edit="${i}">Edit record</button><button class="plain-button" data-delete="${i}">Remove draft record</button></article>`).join(''):'<p class="empty-state">No matching records. Add a record above or clear your search.</p>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing=Number(b.dataset.edit);render();document.querySelector('#demo-0').focus();});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const index=Number(b.dataset.delete),removed=rows.splice(index,1)[0];editing=null;persist();render();const status=document.querySelector('#demo-status');status.textContent=error||'Draft removed. ';const undo=document.createElement('button');undo.className='plain-button';undo.textContent='Undo';undo.onclick=()=>{rows.splice(index,0,removed);persist();render();};status.append(undo);});}
 render();
 window.addEventListener('storage',event=>{if(event.key===product.dataNamespace){error='This tool changed in another tab. Reload to see the latest records before editing.';root.querySelectorAll('input,button').forEach(x=>x.disabled=true);document.querySelector('#demo-status').textContent=error;}});
}
