import {module,lesson,review,field} from './kit.js';
const meal=['meal-strategy'];
export default module({
 id:6,slug:'meal',phase:'Prove & Show',title:'MEAL: Monitoring, Evaluation, Accountability & Learning',
 short:'Theory of Change → results framework → indicators → data → learning → decisions',
 intro:'Turn your Theory of Change into evidence you can use. Build a results framework, define indicators with honest baselines and targets, collect data ethically, listen to the people you serve, evaluate what matters and use what you learn to make better decisions. The same principles apply to programme MEAL in nonprofits and to impact measurement in social enterprises and startups.',
 output:'MEAL Framework',uses:[1,2,5],
 workbook:{file:'Module-06-MEAL.xlsx',title:'MEAL workbook'},
 promo:{lesson:'monitoring',tools:['meal-strategy','theory-of-change'],
  headline:'Compare planned and actual results every quarter, without rebuilding spreadsheets',
  pitch:'MEAL Strategy keeps every indicator with its definition, baseline, target, data source and owner, tracks planned against actual each quarter and records the learning and decisions from each review. It can pull indicators from your Theory of Change and KPIs from your annual plan.'},
 lessons:[
 lesson({id:'system',title:'MEAL principles and a proportionate system',stage:'Understand',sheet:'MEAL plan',tools:meal,
  learn:[
  'Monitoring tracks what is happening regularly. Evaluation examines questions about whether, how and why results occur. Accountability means the people you serve can influence the work and raise concerns. Learning means using findings to change decisions. Together they answer: are we doing what we said, is it making a difference, and what should we change?',
  'Nonprofit programmes usually use results frameworks, logframes and donor reporting. Social enterprises and startups often speak of impact measurement, outcome metrics and product analytics. The underlying principles are the same: define the change, measure it honestly, listen to the people affected and act on what you learn. Use the vocabulary your stakeholders understand.',
  'Make the system proportionate. Collect only data you will use for a decision or obligation, and that you can collect and protect responsibly. A small organisation with five good indicators reviewed every quarter learns more than one with fifty indicators nobody analyses.',
  'The chain that runs through this module is: Theory of Change → results framework → indicators → data → learning → decisions. Each lesson adds one link.'
  ],
  weak:'Collect as much data as possible.',
  strong:'A tutoring project checks reading progress monthly, asks families about access barriers and adjusts session times at a termly review.',
  why:'Each information source supports a decision.',
  reflect:'Which decision will your next data collection inform?',
  exercise:'Write the purpose of your MEAL system and the decisions it must inform.',
  fields:[field('purpose','Purpose of our MEAL system','What questions it must answer and for whom.'),field('decisions','Decisions MEAL should inform','Decision | who makes it | when | what evidence they need.')],
  check:'Is every part of your system linked to a decision or an obligation?'}),
 lesson({id:'results-framework',title:'From Theory of Change to results framework',stage:'Design',sheet:'Results framework',tools:['meal-strategy','theory-of-change'],
  learn:[
  'A results framework turns your Theory of Change into a structured table: for each external objective, the expected impact, outcomes and outputs, each with indicators, sources of evidence and assumptions. A logframe is a common donor version of the same idea, usually with a narrative column, indicators, means of verification and assumptions.',
  'Start from your pathways in Module 2. Copy the outcomes and outputs you will actually monitor, not every box in the diagram. Keep the codes from your strategy (for example ESO1, Outcome 1.1, Output 1.1.1) so results, budgets and plans can be linked.',
  'Check the vertical logic (if outputs are delivered and assumptions hold, do outcomes follow?) and the horizontal logic (is each result measurable with the evidence you can obtain?).'
  ],
  weak:'Our logframe is the activity plan with numbers.',
  strong:'ESO1 → Outcome 1.1 “Graduates demonstrate job-relevant skills” → Outputs 1.1.1 “Sessions delivered”, 1.1.2 “Mentors trained”, each with evidence source and assumptions carried over from the Theory of Change.',
  why:'The stronger framework follows the pathway and keeps codes that connect to strategy and budgets.',
  reflect:'Which outcome in your Theory of Change are you not planning to monitor, and why?',
  exercise:'Build your results framework for one external objective.',
  fields:[field('framework','Results framework','Code | level (impact, outcome, output) | result statement | evidence source | assumption.')],
  check:'Does every result trace back to a pathway in your Theory of Change?'}),
 lesson({id:'indicators',title:'Indicators',stage:'Design',sheet:'Indicators',tools:meal,
  learn:[
  'An indicator is a specific sign you will track to show whether a result is happening. It should be clearly defined, measurable with available data, relevant to the result and sensitive to change. Write a short definition so two people would measure it the same way.',
  'Mix quantitative indicators (numbers, percentages) with qualitative ones (changes described by people, stories of change, observed practice). For percentages, define the numerator and the denominator. Decide how you will disaggregate, for example by gender, age, disability or location, so that unequal results are visible.',
  'Watch for common traps: counting activities as outcomes, indicators that reward easy numbers, double counting the same person across activities, and indicators you cannot collect ethically. Record each indicator in an indicator reference sheet with definition, unit, source, method, frequency, owner and direction (higher or lower is better).'
  ],
  weak:'Number of people empowered.',
  strong:'Percentage of graduates in paid work or training six months after completing the programme (numerator: graduates in work or training at follow-up; denominator: all graduates reached at follow-up), disaggregated by gender and care experience.',
  why:'The stronger indicator is defined, measurable and disaggregated.',
  reflect:'Which of your indicators could improve while the real situation gets worse?',
  exercise:'Define indicators for your priority results.',
  fields:[field('indicators','Indicator reference sheet','Code | result | indicator | definition | unit | numerator/denominator | disaggregation | source | frequency | owner.')],
  check:'Would two people measure each indicator the same way from its definition?'}),
 lesson({id:'baselines',title:'Baselines and targets',stage:'Design',sheet:'Indicators',tools:meal,
  learn:[
  'A baseline is the value of an indicator before your work starts, or at a fixed starting point. A target is the value you aim to reach by a given date. Without a baseline, you cannot show change; without a target, you cannot judge progress.',
  'If you do not know the baseline, do not invent it. Plan how and when you will establish it: an intake survey, existing records, a first-quarter measurement or published data. Record “to be established by [date]” until you have it.',
  'Set targets that are ambitious but realistic, using evidence from similar work, your capacity and the time change usually takes. Break annual targets into quarterly milestones where that helps management. Revise targets openly, with a reason, rather than quietly.'
  ],
  weak:'Target: 100% success.',
  strong:'Baseline to be established from intake assessments in Q1. Provisional target: 60% of graduates in work or training at six months by year end, to be confirmed after the baseline.',
  why:'The stronger example refuses to invent a baseline and sets a provisional, reviewable target.',
  reflect:'Which of your targets is based on hope rather than evidence?',
  exercise:'Set baselines (or baseline plans) and targets for your indicators.',
  fields:[field('targets','Baselines and targets','Indicator | baseline or plan to establish it | target | date | quarterly milestones | evidence for the target.')],
  check:'Is every baseline either measured or planned, never invented?'}),
 lesson({id:'data-collection',title:'Data collection, ethics and data quality',stage:'Implement',sheet:'Data collection plan',
  learn:[
  'Choose methods that fit the indicator and the people involved: registers and attendance, surveys, interviews, focus groups, observation, tests of skill, administrative records, digital analytics. Use the simplest method that gives credible evidence.',
  'Collect data ethically. Explain why you collect it, obtain informed consent, collect the minimum necessary, protect confidentiality, make participation voluntary and avoid causing distress. Take particular care with children, vulnerable adults and sensitive topics, and follow your data protection rules.',
  'Data quality has five checks: validity (it measures what it claims), reliability (it is collected consistently), timeliness, precision and integrity (it has not been altered). Build simple checks into your process: training for data collectors, spot checks and clear definitions.',
  'Design tools with the people who will use them and test them before rolling out.'
  ],
  weak:'Send a long survey to everyone at the end.',
  strong:'Short intake and six-month follow-up phone survey with consent script; attendance register; skill observation checklist used by trained mentors; 10% of records spot-checked each quarter.',
  why:'The stronger plan matches methods to indicators, includes consent and builds in quality checks.',
  reflect:'What data are you collecting that you never use?',
  exercise:'Draft your data collection plan.',
  fields:[field('plan','Data collection plan','Indicator | method and tool | who collects | when | consent approach | where stored.'),field('quality','Quality checks','How you will check validity, reliability and integrity.')],
  check:'Does each method protect participants and produce data you can trust?'}),
 lesson({id:'meal-plan',title:'The MEAL plan and budget',stage:'Implement',sheet:'MEAL plan',tools:meal,
  learn:[
  'A MEAL plan brings everything together: the results framework, indicators, data collection, roles, timing, review meetings, evaluation plans, accountability mechanisms and reporting. It is the operating manual for your evidence.',
  'Assign roles clearly. Who collects data, who enters and checks it, who analyses it, who leads reviews and who reports? In small organisations one person may do much of this; make the time visible.',
  'Budget for MEAL. Data collection tools, staff time, participant compensation, translation, evaluation and learning events all cost money. Many funders accept a MEAL budget line; include it in your proposals and in Module 9.'
  ],
  weak:'Monitoring will be done by everyone when they have time.',
  strong:'Delivery lead collects and enters data weekly; director reviews quarterly; external evaluator in year 3; MEAL budget of 7% of programme costs.',
  why:'Roles, timing and resources are explicit.',
  reflect:'Who in your team has the time to analyse data, not just collect it?',
  exercise:'Write the roles, calendar and budget for your MEAL system.',
  fields:[field('roles','Roles and responsibilities','Task | who | time needed.'),field('calendar','MEAL calendar','Activity | frequency | dates.'),field('budget','MEAL budget','Item | estimated cost | funding source.')],
  check:'Are MEAL roles and costs visible in plans and budgets?'}),
 lesson({id:'monitoring',title:'Monitoring: planned versus actual',stage:'Manage',sheet:['Indicators','Reviews'],tools:meal,
  learn:[
  'Monitoring compares what you planned with what is happening. For each indicator and period, record the planned value, the actual value and the difference. Look at trends over several periods, not just one number.',
  'When there is a gap, ask why before reacting. Is the data correct? Did an assumption fail? Did the context change? Is the target unrealistic? Separate the explanation from the response.',
  'Present monitoring data simply: a dashboard with a few indicators, traffic-light status and a short commentary. Share it with the people who can act on it, including frontline staff and, where appropriate, participants.'
  ],
  weak:'We report numbers at the end of the year.',
  strong:'Quarterly dashboard: planned vs actual for eight indicators, traffic-light status and two lines of explanation for each red item, discussed at the quarterly review.',
  why:'Monitoring is regular, visual and connected to explanation and review.',
  reflect:'If an indicator turned red tomorrow, who would notice and what would they do?',
  exercise:'Design your monitoring dashboard and the routine for reviewing it.',
  fields:[field('dashboard','Monitoring dashboard','Indicator | target | planned this period | actual | status | comment.'),field('routine','Monitoring routine','Who prepares, who reviews, how often and what happens to red items.')],
  check:'Does every gap between planned and actual lead to an explanation and, if needed, an action?'}),
 lesson({id:'evaluation',title:'Evaluation',stage:'Review',sheet:'Evaluation plan',
  learn:[
  'Evaluation asks deeper questions than monitoring: did the work achieve its outcomes, for whom, why, at what cost and with what unintended effects? Common criteria are relevance, coherence, effectiveness, efficiency, impact and sustainability.',
  'Choose the type of evaluation for your purpose: formative (to improve during delivery), summative (to judge results at the end), process (to understand how delivery works) or impact (to estimate the difference made compared with what would otherwise have happened). Rigorous impact evaluation is expensive; many organisations rely on credible contribution stories.',
  'Decide whether to evaluate internally or commission an external evaluator. External evaluations bring independence but need terms of reference, budget and management time. Plan how you will use and publish the findings, and how you will respond to recommendations.'
  ],
  weak:'We will do an impact evaluation when we have money.',
  strong:'Light internal mid-term review in month 18 (process and early outcomes); external final evaluation in year 3 with three questions agreed with participants and funders; management response to every recommendation.',
  why:'The stronger plan matches evaluation type to purpose and commits to using the findings.',
  reflect:'What is the one question about your work you most need an honest answer to?',
  exercise:'Draft your evaluation plan.',
  fields:[field('questions','Evaluation questions','The three to five questions you most need answered.'),field('approach','Type, timing and who','Formative or summative, internal or external, timing and budget.'),field('use','Using the findings','How findings will be shared, discussed and acted on.')],
  check:'Will your evaluation answer questions that lead to decisions?'}),
 lesson({id:'accountability',title:'Accountability: participation, feedback and complaints',stage:'Implement',sheet:'Feedback log',
  learn:[
  'Accountability to the people you serve means sharing information they can understand, involving them in decisions that affect them, listening to their feedback and handling complaints fairly. It respects people’s dignity and improves the work.',
  'Offer several feedback channels suited to different people: conversations, suggestion boxes, phone lines, messaging, surveys and community meetings. Include at least one route outside the immediate delivery team for sensitive concerns, including safeguarding.',
  'Record feedback and complaints, respond within agreed times and close the loop: tell people what changed because of their feedback, or why it could not. Analyse feedback regularly for patterns. Sensitive complaints, such as abuse or fraud, follow the procedures in Module 10.'
  ],
  weak:'People can always talk to us.',
  strong:'Three channels (session feedback cards, a phone number answered by the operations lead, a quarterly participant forum); responses within ten working days; a “you said, we did” notice each quarter.',
  why:'Channels are accessible, independent of the delivery team and visibly lead to action.',
  reflect:'What would stop a participant from complaining about your organisation?',
  exercise:'Design your feedback and complaints mechanism.',
  fields:[field('channels','Feedback channels','Channel | who it suits | who receives it | response time.'),field('loop','Closing the loop','How you record, analyse, respond and report back.')],
  check:'Could someone raise a sensitive concern without going through the person concerned?'}),
 lesson({id:'learning',title:'Learning and adaptive management',stage:'Manage',sheet:'Reviews',tools:meal,
  learn:[
  'Learning is the step that turns evidence into better decisions. It needs time set aside: regular review meetings where the team looks at monitoring data, feedback and evaluation findings and asks “so what?” and “now what?”',
  'Use simple formats: an after-action review (what was planned, what happened, why, what we will do differently), a quarterly learning session, a lessons log. Record decisions with an owner and a date, and check at the next review whether they were carried out.',
  'Adaptive management means changing activities, targets or even the Theory of Change in response to evidence, transparently and with the agreement of the people who need to agree, including funders when required. Treat negative findings as useful information rather than failures to hide.'
  ],
  weak:'We discuss lessons learned in the final report.',
  strong:'Quarterly learning session using the dashboard and feedback log; each session records two to three decisions with owners; the Theory of Change is updated after the annual review.',
  why:'Learning is scheduled, recorded and connected to decisions.',
  reflect:'What is the last decision you changed because of evidence?',
  exercise:'Plan your learning routine and record a first review.',
  fields:[field('routine','Learning routine','Format, frequency, participants and how decisions are recorded.'),field('review','First review record','Finding | feedback | learning | decision | owner | due.')],
  check:'Does each review end with recorded decisions that someone owns?'}),
 lesson({id:'reporting',title:'Reporting and communicating evidence',stage:'Review',sheet:'Reporting plan',
  learn:[
  'Different audiences need different reports: the board needs a concise dashboard and risks; funders need agreed formats and deadlines; participants and communities need accessible feedback; the public needs honest, simple stories backed by evidence.',
  'Report honestly. Distinguish outputs from outcomes, contribution from attribution, and evidence from aspiration. Include what did not work and what you changed. Credibility is built by consistency between what you claim and what your data shows.',
  'Plan reporting in your calendar and reuse data rather than recreating it. Module 8 shows how to turn evidence into communications, and Module 11 how to report to funders.'
  ],
  weak:'Our programme transformed hundreds of lives.',
  strong:'This year 84 young people completed the programme; 52% of those we reached at six months were in work or training (baseline 31%). Transport costs remained a barrier, so next year we are piloting travel support.',
  why:'The stronger report is specific, honest about limits and shows learning.',
  reflect:'Which claim you currently make could you not support with evidence?',
  exercise:'Build your reporting plan by audience.',
  fields:[field('plan','Reporting plan','Audience | what they need | format | frequency | owner.'),field('claims','Evidence behind our main claims','Claim | evidence | limits.')],
  check:'Could you show the evidence behind every claim in your reports?'}),
 review('meal-framework','Your MEAL Framework')
 ]
});
